### ISSUE TITLE
v1.0.0.5 (pulled from ivy). Vaadin version 7.4.5. 

### ISSUE THREAD

**Issue by ghost** [sameeraroshan/visjs#14]
The vis doesn't "run" at all, but the following just pops, when the mouse is over the visualizaiton area.

com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.AbstractMethodError: org.vaadin.visjs.networkDiagram.NetworkDiagram$5.call(Lelemental/json/JsonArray;)V
    at com.vaadin.server.JavaScriptCallbackHelper$1.call(JavaScriptCallbackHelper.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
    at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:176)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:255)
    at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:58)
    at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:78)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
    at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:332)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:327)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:424)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:794)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:526)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:104)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:190)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:138)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:599)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by sameeraroshan** [comment]
use vaadin version below 7.4 since the vaadin api is changed with 7.4+. ill add the support for 7.4+ with new enhancement.

**Comment by ghost** [comment]
I thought that this --> 

"Swoorup Joshi – May 28, 2015 5:28 PM
I think I have fixed issues on vaadin versions > 7.4. The fix was quite easy with some help from the upstream developers. I have put my changes onto https://github.com/Swoorup/visjs"  

which was posted on https://vaadin.com/directory#!addon/visjs-addon, was refering to vaadin 7.4 version and newer for your original project, so I pulled it with one version higher in IVY thinking it'll be the one with the fix. Sorry!

**Comment by sameeraroshan** [comment]
issue is fixed in version 1.0.1.0

**Comment by ghost** [comment]
yes I saw it, already using it. Thank you very much!

**Comment by ghost** [comment]
Just letting you know, I've noticed it runs ok but in the browser's console it throws the following:

Sat Jun 06 20:26:44 GMT+300 2015 com.vaadin.client.ApplicationConnection
SEVERE: Error sending state change eventscom.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'redraw' of undefined
    at Unknown.Wj(thesis.widgetset.ThesisWidgetset-0.js)
    at Unknown.$j(thesis.widgetset.ThesisWidgetset-0.js) ........
......
at Unknown.jQuery.atmosphere.AtmosphereRequest._websocket.onmessage(http://localhost/Thesis/VAADIN/vaadinPush.debug.js?v=7.4.5)

And,

Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'redraw' of undefined
    at Unknown.hjb(thesis.widgetset.ThesisWidgetset-0.js)
.......
at Unknown.jQuery.atmosphere.AtmosphereRequest._websocket.onmessage(http://localhost/Thesis/VAADIN/vaadinPush.debug.js?v=7.4.5)

And This in the IDE's console

com.vaadin.server.communication.PublishedFileHandler handleRequest
WARNING: Rejecting published file request for file that has not been published: js/vis.map
