### ISSUE TITLE
Switching between views causes graph to dissapear

### ISSUE THREAD

**Issue by daiselan** [sameeraroshan/visjs#6]
Steps
1. Create the network diagram in a view (similar to a view in vaadin quick tickets dashboard)
2. Create another component like a vaadin tree in another view
3. Initially both the views work
4. Switch back from network diagram view to tree view and come back again to network diagram view
5. The network diagram disappears
logs say this "WARNING: RPC call to com.vaadin.ui.JavaScript$JavaScriptCallbackRpc.call received for connector 118 but no such connector could be found. Resynchronizing client."

**Comment by daiselan** [comment]
Fri Mar 13 09:29:44 GMT-700 2015 com.vaadin.client.VConsole
SEVERE: Exception caught: (TypeError) : graph is undefinedcom.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : graph is undefined
    at Unknown.java_lang_Throwable_fillInStackTrace__Ljava_lang_Throwable_2(Unknown Source)
    at Unknown.java_lang_Throwable_Throwable__Ljava_lang_String_2Ljava_lang_Throwable_2V(Unknown Source)
    at Unknown.java_lang_Exception_Exception__Ljava_lang_String_2Ljava_lang_Throwable_2V(Unknown Source)
    at Unknown.java_lang_RuntimeException_RuntimeException__Ljava_lang_String_2Ljava_lang_Throwable_2V(Unknown Source)
    at Unknown.com_google_web_bindery_event_shared_UmbrellaException_UmbrellaException__Ljava_util_Set_2V(Unknown Source)
    at Unknown.com_google_gwt_event_shared_UmbrellaException_UmbrellaException__Ljava_util_Set_2V(Unknown Source)
    at Unknown.com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(Unknown Source)
    at Unknown.com_vaadin_client_ui_AbstractConnector_$fireEvent__Lcom_vaadin_client_ui_AbstractConnector_2Lcom_google_gwt_event_shared_GwtEvent_2V(Unknown Source)
    at Unknown.com_vaadin_client_ui_AbstractConnector_fireEvent__Lcom_google_gwt_event_shared_GwtEvent_2V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection$9_$sendStateChangeEvents__Lcom_vaadin_client_ApplicationConnection$9_2Lcom_vaadin_client_JsArrayObject_2V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection$9_execute__V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConfiguration_runWhenDependenciesLoaded__Lcom_google_gwt_user_client_Command_2V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection_$handleUIDLMessage__Lcom_vaadin_client_ApplicationConnection_2Ljava_util_Date_2Ljava_lang_String_2Lcom_vaadin_client_ValueMap_2V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection_$handleReceivedJSONMessage__Lcom_vaadin_client_ApplicationConnection_2Ljava_util_Date_2Ljava_lang_String_2Lcom_vaadin_client_ValueMap_2V(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection_$handleJSONText__Lcom_vaadin_client_ApplicationConnection_2Ljava_lang_String_2IV(Unknown Source)
    at Unknown.com_vaadin_client_ApplicationConnection$5_onResponseReceived__Lcom_google_gwt_http_client_Request_2Lcom_google_gwt_http_client_Response_2V(Unknown Source)
    at Unknown.com_google_gwt_http_client_Request_$fireOnResponseReceived__Lcom_google_gwt_http_client_Request_2Lcom_google_gwt_http_client_RequestCallback_2V(Unknown Source)
    at Unknown.com_google_gwt_http_client_RequestBuilder$1_onReadyStateChange__Lcom_google_gwt_xhr_client_XMLHttpRequest_2V(Unknown Source)
    at Unknown.anonymous(Unknown Source)
    at Unknown.com_google_gwt_core_client_impl_Impl_apply__Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2(Unknown Source)
    at Unknown.com_google_gwt_core_client_impl_Impl_entry0__Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2(Unknown Source)
    at Unknown.anonymous(Unknown Source)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : graph is undefined

**Comment by sempervivo** [comment]
Hi,

How did you fix it ? I have the same problem.
